<?php
// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/companies.php");
	include("$currDir/companies_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('companies');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "companies";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`companies`.`id`" => "id",
		"`companies`.`name`" => "name",
		"IF(    CHAR_LENGTH(`compnayTypes1`.`type`), CONCAT_WS('',   `compnayTypes1`.`type`), '') /* Company Type */" => "type",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`companies`.`id`',
		2 => 2,
		3 => '`compnayTypes1`.`type`',
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`companies`.`id`" => "id",
		"`companies`.`name`" => "name",
		"IF(    CHAR_LENGTH(`compnayTypes1`.`type`), CONCAT_WS('',   `compnayTypes1`.`type`), '') /* Company Type */" => "type",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`companies`.`id`" => "ID",
		"`companies`.`name`" => "Name",
		"IF(    CHAR_LENGTH(`compnayTypes1`.`type`), CONCAT_WS('',   `compnayTypes1`.`type`), '') /* Company Type */" => "Company Type",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`companies`.`id`" => "id",
		"`companies`.`name`" => "name",
		"IF(    CHAR_LENGTH(`compnayTypes1`.`type`), CONCAT_WS('',   `compnayTypes1`.`type`), '') /* Company Type */" => "type",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('type' => 'Company Type', );

	$x->QueryFrom = "`companies` LEFT JOIN `compnayTypes` as compnayTypes1 ON `compnayTypes1`.`id`=`companies`.`type` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "companies_view.php";
	$x->RedirectAfterInsert = "companies_view.php?SelectedID=#ID#";
	$x->TableTitle = "Companies";
	$x->TableIcon = "resources/table_icons/balance.png";
	$x->PrimaryKey = "`companies`.`id`";

	$x->ColWidth   = array(  150, 150);
	$x->ColCaption = array("Name", "Company Type");
	$x->ColFieldName = array('name', 'type');
	$x->ColNumber  = array(2, 3);

	// template paths below are based on the app main directory
	$x->Template = 'templates/companies_templateTV.html';
	$x->SelectedTemplate = 'templates/companies_templateTVS.html';
	$x->TemplateDV = 'templates/companies_templateDV.html';
	$x->TemplateDVP = 'templates/companies_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `companies`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='companies' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `companies`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='companies' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`companies`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: companies_init
	$render=TRUE;
	if(function_exists('companies_init')) {
		$args=array();
		$render=companies_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: companies_header
	$headerCode='';
	if(function_exists('companies_header')) {
		$args=array();
		$headerCode=companies_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: companies_footer
	$footerCode='';
	if(function_exists('companies_footer')) {
		$args=array();
		$footerCode=companies_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>