<?php
// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/todoList.php");
	include("$currDir/todoList_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('todoList');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "todoList";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`todoList`.`id`" => "id",
		"`todoList`.`task`" => "task",
		"`todoList`.`taskReady`" => "taskReady",
		"if(`todoList`.`reminder`,date_format(`todoList`.`reminder`,'%m/%d/%Y'),'')" => "reminder",
		"TIME_FORMAT(`todoList`.`reminder_time`, '%r')" => "reminder_time",
		"`todoList`.`prority`" => "prority",
		"`todoList`.`notes`" => "notes",
		"`todoList`.`order`" => "order",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`todoList`.`id`',
		2 => 2,
		3 => '`todoList`.`taskReady`',
		4 => '`todoList`.`reminder`',
		5 => '`todoList`.`reminder_time`',
		6 => 6,
		7 => 7,
		8 => '`todoList`.`order`',
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`todoList`.`id`" => "id",
		"`todoList`.`task`" => "task",
		"`todoList`.`taskReady`" => "taskReady",
		"if(`todoList`.`reminder`,date_format(`todoList`.`reminder`,'%m/%d/%Y'),'')" => "reminder",
		"TIME_FORMAT(`todoList`.`reminder_time`, '%r')" => "reminder_time",
		"`todoList`.`prority`" => "prority",
		"`todoList`.`notes`" => "notes",
		"`todoList`.`order`" => "order",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`todoList`.`id`" => "ID",
		"`todoList`.`task`" => "Task",
		"`todoList`.`taskReady`" => "TaskReady",
		"`todoList`.`reminder`" => "Time",
		"`todoList`.`reminder_time`" => "Reminder time",
		"`todoList`.`prority`" => "Prority",
		"`todoList`.`notes`" => "Notes",
		"`todoList`.`order`" => "Order",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`todoList`.`id`" => "id",
		"`todoList`.`task`" => "task",
		"`todoList`.`taskReady`" => "taskReady",
		"if(`todoList`.`reminder`,date_format(`todoList`.`reminder`,'%m/%d/%Y'),'')" => "reminder",
		"TIME_FORMAT(`todoList`.`reminder_time`, '%r')" => "reminder_time",
		"`todoList`.`prority`" => "prority",
		"`todoList`.`notes`" => "notes",
		"`todoList`.`order`" => "order",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`todoList` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "todoList_view.php";
	$x->RedirectAfterInsert = "todoList_view.php?SelectedID=#ID#";
	$x->TableTitle = "TodoList";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`todoList`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Task", "TaskReady", "Time", "Reminder time", "Prority", "Notes", "Order");
	$x->ColFieldName = array('task', 'taskReady', 'reminder', 'reminder_time', 'prority', 'notes', 'order');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8);

	// template paths below are based on the app main directory
	$x->Template = 'templates/todoList_templateTV.html';
	$x->SelectedTemplate = 'templates/todoList_templateTVS.html';
	$x->TemplateDV = 'templates/todoList_templateDV.html';
	$x->TemplateDVP = 'templates/todoList_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `todoList`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='todoList' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `todoList`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='todoList' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`todoList`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: todoList_init
	$render=TRUE;
	if(function_exists('todoList_init')) {
		$args=array();
		$render=todoList_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: todoList_header
	$headerCode='';
	if(function_exists('todoList_header')) {
		$args=array();
		$headerCode=todoList_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: todoList_footer
	$footerCode='';
	if(function_exists('todoList_footer')) {
		$args=array();
		$footerCode=todoList_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>